name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-12.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'motorola/kansas'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'kansas'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'twrp_kansas'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'recovery'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout Work
      uses: actions/checkout@v4

    - name: Prepare Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo

    - name: Initialize and Sync Minimal AOSP
      run: |
        export PATH=/usr/bin:$PATH
        rm -rf workspace
        mkdir workspace
        cd workspace
        repo init -u https://github.com -b twrp-12.1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Inject Personal Device Configs
      run: |
        mkdir -p workspace/${{ github.event.inputs.DEVICE_PATH }}
        cp -r motorola/kansas/* workspace/${{ github.event.inputs.DEVICE_PATH }}/
        
        mkdir -p workspace/vendor/motorola/kansas
        cp -r vendor/motorola/kansas/* workspace/vendor/motorola/kansas/

    - name: Execute TWRP Compilation Run
      run: |
        export PATH=/usr/bin:$PATH
        cd workspace
        source build/envsetup.sh
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng || lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)

    - name: Upload Finished Recovery Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-${{ github.event.inputs.DEVICE_NAME }}-image
        path: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.img

